GeneratorCSV/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('', include('data_schemas.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_schemas/forms.py
from django import forms
from .models import Schema, Dataset


TYPE_CHOICES = (
    (1, "Integer"),
    (2, "Fullname"),
    (3, "Email"),
    (4, "Job"),
    (5, "Date"),
)


class SchemaForm(forms.ModelForm):
    schema_title = forms.CharField(label='Schema title', required=True,
                                   widget=forms.TextInput(attrs={'class': 'form-control'}))
    separator = forms.ChoiceField(choices=Schema.Separator.choices, initial='', label='Column separator', required=True,
                                  widget=forms.Select(attrs={'class': 'type_dropdown form-select'}))
    string_char = forms.ChoiceField(choices=Schema.StringCharacter.choices, initial='', label='String character',
                                    required=True,
                                    widget=forms.Select(attrs={'class': 'type_dropdown form-select'}))

    class Meta:
        model = Schema
        fields = ['schema_title', 'separator', 'string_char']

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean(self):
        data = self.cleaned_data
        all_user_schemes = Schema.objects.filter(owner_id=self.user.id).values_list('title')
        for i in all_user_schemes:
            if data['schema_title'] == i[0]:
                raise forms.ValidationError("Title should be unique")
        return data


class TypeFieldForm(forms.Form):
    title = forms.CharField(label='Title', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    type = forms.ChoiceField(choices=TYPE_CHOICES, label="Field type", initial='',
                             widget=forms.Select(attrs={'class': 'type_dropdown form-select'}), required=True)
    min_value_range = forms.IntegerField(label="From", required=False,
                                         widget=forms.NumberInput(attrs={'class': 'form-control min_range_input'}))
    max_value_range = forms.IntegerField(label="To", required=False,
                                         widget=forms.NumberInput(attrs={'class': 'form-control max_range_input'}))
    order_nmb = forms.IntegerField(label="Order number", required=True,
                                   widget=forms.NumberInput(attrs={'class': 'form-control'}))


class DatasetForm(forms.ModelForm):
    rows_counter = forms.IntegerField(label="Rows", required=True,
                                      widget=forms.TextInput(attrs={'class': 'form-control rows-form'}, ))

    class Meta:
        model = Dataset
        fields = ['rows_counter']

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <title>{% block title %}{% endblock title %}</title>
    </head>

    <body class="Site">

        <div class="site-wrapper h-100">
            <div class="site-wrapper-content h-100">
                    {% block content %}
                    {% endblock content %}
            </div>
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>

    <script>
        {
            const mydata = `<div class="row mt-3 field-type-row">
                    {% for field in form %}
                    <div class="col-2">
                        <div>{{ field.label }}</div>
                        <div>{{ field }}</div>
                    </div>
                    {% endfor %}
                <div class="col-1 text-center">
                   <button class="deletebtn" type="button">Delete</button>
                </div>
                </div>`.replace('id="id_max_value_range"', 'id="id_max_value_range" required="required"'
            ).replace('id="id_min_value_range"', 'id="id_min_value_range" required="required"')


            $(".appendbtn").click(function () {
               $('#schema-fields-div').append(mydata);
            });
        }
        {
            $(document).ready ( function () {
                $(document).on ("click", ".deletebtn", function () {
                    $(this).closest('.field-type-row').remove();
                });
            });
        }
    </script>

    <script>
        {
            function CheckFieldOnRange(){
                if ( !['1'].includes(obj.children('option:selected').val())) {
                    console.log("efr")
                    obj.closest('.field-type-row').find("#id_max_value_range").attr("required", false)
                    obj.closest('.field-type-row').find("#id_min_value_range").attr("required", false)
                    obj.closest('.field-type-row').find("#id_max_value_range").closest('.col-2').css('visibility', 'hidden');
                    obj.closest('.field-type-row').find("#id_min_value_range").closest('.col-2').css('visibility', 'hidden');
                }else {
                    console.log("233")
                    obj.closest('.field-type-row').find("#id_max_value_range").attr("required", true)
                    obj.closest('.field-type-row').find("#id_min_value_range").attr("required", true)
                    obj.closest('.field-type-row').find("#id_max_value_range").closest('.col-2').css('visibility', 'visible');
                    obj.closest('.field-type-row').find("#id_min_value_range").closest('.col-2').css('visibility', 'visible');
                }
            }

            $(document).ready(function() {
                $('#id_type').each(function (){
                    obj = $(this)
                    CheckFieldOnRange(obj)
                })
            });

            $(document).on('change', '[id^="id_type"]', function(){
                obj = $(this)
                CheckFieldOnRange(obj)
            })
        }
    </script>
    <script>
        {
            $('#schema-field-form').submit(function(e){
                $(".min_range_input").each(function () {
                            let min_r = parseInt($(this).val())
                            let max_r = parseInt($(this).closest('.field-type-row').find('.max_range_input').val())

                            if (min_r >= max_r) {
                                e.preventDefault()
                                window.alert("Min range value should be less than max value");
                                return false
                            }
                        })
                  })
         }
    </script>
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a href="/" class="navbar-brand">FakeCSV</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Schemas</a>
        </li>
      </ul>
    </div>

      <div>
          <span class="navbar-text p-2">Hello, <b>{{ request.user.username }}</b></span>
          <a class="navbar-text p-2" style="text-decoration: none" href="{% url 'logout' %}">Logout</a>
      </div>
  </div>
</nav>